const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgresql://postgres:Septapumasurya01@db.rmhyamsztnskwxlbyrhl.supabase.co:5432/postgres'
});

async function run() {
  await client.connect();
  const sql = `
CREATE TABLE IF NOT EXISTS prediction_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT NOT NULL,
  target_timestamp TIMESTAMPTZ NOT NULL,
  pred_r FLOAT NOT NULL,
  pred_s FLOAT NOT NULL,
  pred_t FLOAT NOT NULL,
  rf_status TEXT,
  confidence FLOAT,
  action TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(device_id, target_timestamp)
);
  `;
  await client.query(sql);
  console.log('Table created successfully.');
  
  // Need to reload the schema cache so PostgREST picks up the new table
  await client.query("NOTIFY pgrst, 'reload schema'");
  console.log('Schema cache reloaded.');
  
  await client.end();
}
run().catch(console.error);
